### ISSUE TITLE
csv files

### ISSUE THREAD

**Issue by brookhuang16211** [piotrjurkiewicz/generic-dijkstra#1]
Sorry, I try to validate your simulation results for a long time but no progress. I am wondering if you could kindly send me the csv files mentioned in your project and the necessary information about it. Thanks for your time!

**Comment by piotrjurkiewicz** [comment]
The CSV files contained statistics for all node pairs in each topology. They were very big, so I did not commit them into the repository. However, the only thing used from these CSV files was maximum shortest path length for each topology (in order to calibrate modulation reach in simulation). Therefore, I extracted these numbers to TeX files containing typologies statistics and now simulation script reads it from there, so CSV files are not needed anymore.

Moreover, I added shell file containing complete script fro running simulations and plotting results.

Closed by: 5413f710a056a0c50a7c1d33857f05f0e7f7170f
